# To setup locally:
# pip install -r requirements_test.txt
# pre-commit install

## To run this without committing:
# pre-commit run --all-files

# If this fails, you can run it again if it autofixes (eof, whitespace, isort) and it will pass
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: end-of-file-fixer
        stages: [commit]
      - id: trailing-whitespace
        stages: [commit]
      - id: requirements-txt-fixer
        stages: [commit]
  - repo: https://gitlab.com/pycqa/flake8
    rev: '3.8.4'
    hooks:
    -   id: flake8
        entry: flake8 --config test-conf/flake8.ini
        additional_dependencies: [
            'flake8-docstrings==1.5.0'
        ]
  - repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
      - id: black
        stages: [commit]
  - repo: https://github.com/timothycrosley/isort
    rev: 5.6.4
    hooks:
      - id: isort
        entry: isort --sp test-conf
