import { useCallback, useEffect, useState } from 'react';

import Head from 'next/head'
import styles from '../styles/Home.module.scss'

import { NavBar } from '../src/components/NavBar/NavBar';
import { Preview } from '../src/components/Preview/Preview';

import { MovieList } from '../src/components/MovieList/MovieList';

import { useDispatch, useSelector } from 'react-redux';

import { getMovies } from '../src/store/actions';

import { getFilms, getStartButton } from '../src/store/selectors';

export default function Home() {
  const { activeButtonStart, sortStart } = useSelector(getStartButton);
  const [activeButton, setActiveButton] = useState(activeButtonStart);
  const [sort, setSort] = useState(sortStart);

  const movies = useSelector(getFilms);

  const handleClick = useCallback(
    (e) => {
      setActiveButton(e.target.childNodes[0].data);
      getMovies(e.target.childNodes[0].data, sort, dispatch);
    },
    [sort],
  );
  console.log(activeButton)
  const handleSelect = useCallback(
    (value) => {
      setSort(value);
      getMovies(activeButton, value, dispatch);
    },
    [activeButton],
  );
  return (
    <div className={styles.body}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Preview />
      {/* <NavBar activeButton={activeButton} handleClick={handleClick} handleSelect={handleSelect} /> */}
      <MovieList movies={movies} />
    </div>
  )
}
